Repository peckphp/peck, pull requests merged in 2025-01, with the labels that each got.

#107 refactor: sort files with finder
  src/Checkers/FileSystemChecker.php
  src/Checkers/SourceCodeChecker.php
Labels: enhancement

#108 update base whitelist
  stubs/presets/base.stub
Labels: enhancement

#113 refactor: handle possibly corrupted cache
  src/Services/Spellcheckers/Aspell.php
  tests/Unit/Services/AspellTest.php
Labels: bug

#93 refactor: remove old additional reference to class loader to use new …
  src/Console/Commands/CheckCommand.php
Labels: enhancement

#94 fix: phpdoc special characters
  src/Support/SpellcheckFormatter.php
  tests/Unit/Support/SpellcheckFormatterTest.php
Labels: enhancement

#96 Update README.md for CI actions: check OS before running Peck, otherwise actions will fail if Aspell is not installed in that OS
  README.md
Labels: documentation

#116 Added words from Laravel Framework and Horizon
  stubs/presets/base.stub
  stubs/presets/laravel.stub
Labels: presets

#114 Update base.stub, add term 'sms' and remove duplicates
  stubs/presets/base.stub
Labels: presets

#127 Update base.stub
  stubs/presets/base.stub
Labels: enhancement, presets

#88 Feature/test coverage
  tests/Integration/CheckCommandTest.php
  tests/Unit/Plugins/CacheTest.php
Labels: enhancement

#99 feat(check-command): adds the ability to use peck command to check a given string
  src/Console/Commands/CheckCommand.php
  tests/.pest/snapshots/Console/OutputTest/it_may_fail_with_static_text_option.snap
  tests/.pest/snapshots/Console/OutputTest/it_may_pass_with_static_text_option.snap
  tests/Console/OutputTest.php
  tests/Integration/CheckCommandTest.php
Labels: enhancement

#124 refactor: getConstantNames remove useless array flattening and improve filter order
  src/Checkers/SourceCodeChecker.php
Labels: enhancement
